/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import DBO.FungsiQuery;
import DBO.JTextFieldFilter;
import DBO.koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
/**
 *
 * @author yusuf
 */
public class Customer extends javax.swing.JInternalFrame {

    /**
     * Creates new form customer1
     */
    public Customer() {
        initComponents();
        set1();
        setIdCustomer();
        txtNamaCustomer.setDocument(new JTextFieldFilter (50,2));
        txtAlamat.setDocument(new JTextFieldFilter (100,3));
        txtNoTelpon.setDocument(new JTextFieldFilter (15,1));
    }
    
     private void set1(){
        txtIdCustomer.setEditable(false);
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        
    }
    private void setIdCustomer(){
        {
            try{
                koneksi knks = new koneksi();
                Connection con= knks.bukakoneksi();
                Statement st = con.createStatement();
                String sql;
                sql="SELECT id_customer FROM customer ORDER BY id_customer desc";
                ResultSet rs=st.executeQuery(sql);
                
                if(rs.next()){
                    String IdCustomer = rs.getString ("id_customer").substring(3);
                    String no = "" + (Integer.parseInt(IdCustomer) + 1);
                    String nol = "";
                    
                    if (no.length()==1)
                    {nol = "000";}
                    else if (no.length()==2)
                    {nol = "00";}
                    else if (no.length()==3)
                    {nol = "0";}
                    else if (no.length()==4)
                    {nol = "";}
                    txtIdCustomer.setText("ID-" + nol + no);
                }else {
                    txtIdCustomer.setText("ID-0001");
                }
            }catch(Exception exc)
            {exc.printStackTrace();}
        }
           
    }
        
    private void bersih()
    {
     setIdCustomer();
     txtNamaCustomer.setText("");
     txtAlamat.setText("");
     txtNoTelpon.setText("");
    }
    
    FungsiQuery query=new FungsiQuery();
    String [] kolom=new String[4];
    String [] isi=new String[4];
    String [] dataPopup={"","","",""};
    
    public String[] Kolom()
    {
        kolom[0]="id_customer";
        kolom[1]="nama_customer";
        kolom[2]="alamat";
        kolom[3]="no_telpon";
        return kolom;
    }
    
    public String[] Data()
    {
        isi[0]=txtIdCustomer.getText();
        isi[1]=txtNamaCustomer.getText();
        isi[2]=txtAlamat.getText();
        isi[3]=txtNoTelpon.getText();
        return isi;
    }
    
    public void setDataPopup(String[] dataPopup){
        this.dataPopup=dataPopup;
    }
    
     public String[] getDataPopup(){
        return dataPopup;
    }
     public void FilterHuruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(null, "Masukan Hanya Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
      public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardLayOutCustomer = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtIdCustomer = new javax.swing.JTextField();
        txtNamaCustomer = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNoTelpon = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Customer - PT. Sugimoto Presisi Technologi");

        cardLayOutCustomer.setBackground(new java.awt.Color(153, 153, 153));
        cardLayOutCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "From Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("ID. Customer");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 105, 29));
        jPanel11.add(txtIdCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 191, 29));

        txtNamaCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaCustomerKeyTyped(evt);
            }
        });
        jPanel11.add(txtNamaCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Nama Customer");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 105, 29));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setText("No. Telpon");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 105, 29));

        txtNoTelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTelponKeyTyped(evt);
            }
        });
        jPanel11.add(txtNoTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 190, 29));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("Alamat");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 105, 29));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtAlamat);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 191, -1));

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setPreferredSize(new java.awt.Dimension(57, 23));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel12.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 83, 30));

        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel12.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 83, 30));

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel12.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 83, 30));

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel12.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, 83, 30));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 407, 50));

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel11.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 81, 35));

        javax.swing.GroupLayout cardLayOutCustomerLayout = new javax.swing.GroupLayout(cardLayOutCustomer);
        cardLayOutCustomer.setLayout(cardLayOutCustomerLayout);
        cardLayOutCustomerLayout.setHorizontalGroup(
            cardLayOutCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayOutCustomerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cardLayOutCustomerLayout.setVerticalGroup(
            cardLayOutCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayOutCustomerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardLayOutCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardLayOutCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtIdCustomer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Id Customer belum diisi","Perhatian",
            JOptionPane.WARNING_MESSAGE);
            txtIdCustomer.requestFocus();
        }else if(txtNamaCustomer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Customer belum diisi","Perhatian",
            JOptionPane.WARNING_MESSAGE);
            txtNamaCustomer.requestFocus();
        }else if(txtAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Alamat belum diisi","Perhatian",
            JOptionPane.WARNING_MESSAGE);
            txtAlamat.requestFocus();
        }else if(txtNoTelpon.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No Telpon belum diisi","Perhatian",
            JOptionPane.WARNING_MESSAGE);
            txtNoTelpon.requestFocus();
        }else{
                try{
                Object[] options={"Simpan","Lihat Kembali"};
                int n=JOptionPane.showOptionDialog(null, "<html>Yakin<b><i>"
                    +txtIdCustomer.getText()+" "+"</i></b> akan simpan?</html>","Konfirmasi",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
                    if(n==javax.swing.JOptionPane.YES_OPTION){
                        query.InputDetail(Kolom(), Data(), "customer");
                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                        bersih();
                    }
                }catch(Exception exc){
                        System.err.println(exc.getMessage());                    
                }
            }             
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable()
        {
        public void run()
        {
         PopupCustomer dialog=new PopupCustomer(new javax.swing.JFrame(),true);
         dialog.setVisible(true);
         if(dialog.getData()[0].toString().equals(""))
         {
        
         }
        else 
        {
         txtIdCustomer.setText((String) dialog.getData()[0]);
         txtNamaCustomer.setText((String) dialog.getData()[1]);
         txtAlamat.setText((String) dialog.getData()[2]);
         txtNoTelpon.setText((String) dialog.getData()[3]);
         btnSimpan.setEnabled(false);
         btnUbah.setEnabled(true);
         btnHapus.setEnabled(true);
       }
    }
        });
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            Object[] options={"Ubah","Lihat Kembali"};
            int n=JOptionPane.showOptionDialog(null,"<html>Yakin<b><i>"
            +txtIdCustomer.getText()+" "+"</i></b> Akan Diubah ?</html>","Konfirmasi",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(n==javax.swing.JOptionPane.YES_OPTION)
            {
            query.Edit(Kolom(), Data(), "customer","id_customer", txtIdCustomer.getText());
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            bersih();
                }
        }catch(Exception exc){
         System.err.println(exc.getMessage());
                }
        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
            Object[] options={"Hapus","Lihat Kembali"};
            int n=JOptionPane.showOptionDialog(null,"<html>Yakin<b><i>"
            +txtIdCustomer.getText()+" "+"</i></b> Akan Dihapus?</html>","Konfirmasi",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(n==javax.swing.JOptionPane.YES_OPTION)
            {
            query.Hapus("customer","id_customer", txtIdCustomer.getText());
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            bersih();
            set1();
                }
             }
                catch(Exception exc){
                            System.err.println(exc.getMessage());
             }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersih();
        set1();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaCustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaCustomerKeyTyped
        // TODO add your handling code here:
        FilterHuruf(evt);
    }//GEN-LAST:event_txtNamaCustomerKeyTyped

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
        FilterHuruf(evt);
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtNoTelponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTelponKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_txtNoTelponKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel cardLayOutCustomer;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtIdCustomer;
    private javax.swing.JTextField txtNamaCustomer;
    private javax.swing.JTextField txtNoTelpon;
    // End of variables declaration//GEN-END:variables
}
