/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import DBO.koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author yusuf
 */
public class kas extends javax.swing.JInternalFrame {

    /**
     * Creates new form kas
     */
    public kas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPerhari = new javax.swing.JButton();
        btnPerbulan = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnPerhari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPerhari.setText("Laporan Penerimaan Kas");
        btnPerhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerhariActionPerformed(evt);
            }
        });

        btnPerbulan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPerbulan.setText("Laporan Penerimaan Kas Per-Bulan");
        btnPerbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPerbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerhari, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnPerhari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerhariActionPerformed
        // TODO add your handling code here:
        try{

            koneksi knks = new koneksi();
            Connection con= knks.bukakoneksi();
            Statement st = con.createStatement();

            try{
                String path="src/Report/kas.jasper";
                HashMap parameter = new HashMap();
                JasperPrint print = JasperFillManager.fillReport(path, parameter, st.getConnection());
                JasperViewer.viewReport(print,false);
            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada"+ex);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPerhariActionPerformed

    private void btnPerbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbulanActionPerformed
        // TODO add your handling code here:
        try{

            koneksi knks = new koneksi();
            Connection con= knks.bukakoneksi();
            Statement st = con.createStatement();

            try{
                String Response = JOptionPane.showInputDialog(null, "Masukan Bulan /n Contoh : 10",
                    "Laporan Per-Bulan", JOptionPane.QUESTION_MESSAGE);
                String Response1 = JOptionPane.showInputDialog(null, "Masukan Tahun /n Contoh : 2017",
                    "Laporan Per-Bulan", JOptionPane.QUESTION_MESSAGE);
                String path="src/Report/kasbulan.jasper";
                HashMap parameter = new HashMap();
                parameter.put ("pbulan", Response);
                parameter.put ("ptahun", Response1);
                JasperPrint print = JasperFillManager.fillReport(path, parameter, st.getConnection());
                this.dispose();
                JasperViewer.viewReport(print,false);
            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada"+ex);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPerbulanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerbulan;
    private javax.swing.JButton btnPerhari;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
