/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import DBO.koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author yusuf
 */
public class laporan2 extends javax.swing.JDialog {

    /**
     * Creates new form laporan2
     */
    public laporan2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPerhari = new javax.swing.JButton();
        btnPerbulan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnPerhari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPerhari.setText("Laporan Penjualan");
        btnPerhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerhariActionPerformed(evt);
            }
        });

        btnPerbulan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPerbulan.setText("Laporan Per-Bulan");
        btnPerbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPerbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerhari, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnPerhari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPerbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerhariActionPerformed
        // TODO add your handling code here:
        try{

            koneksi knks = new koneksi();
            Connection con= knks.bukakoneksi();
            Statement st = con.createStatement();

            try{
                String path="src/Report/lappenjualan.jasper";
                HashMap parameter = new HashMap();
                JasperPrint print = JasperFillManager.fillReport(path, parameter, st.getConnection());
                this.dispose();
                JasperViewer.viewReport(print,false);
            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada"+ex);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPerhariActionPerformed

    private void btnPerbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbulanActionPerformed
        // TODO add your handling code here:
        try{

            koneksi knks = new koneksi();
            Connection con= knks.bukakoneksi();
            Statement st = con.createStatement();

            try{
                String Response = JOptionPane.showInputDialog(null, "Masukan Bulan /n Contoh : 10",
                        "Laporan Per-Bulan", JOptionPane.QUESTION_MESSAGE);
                String Response1 = JOptionPane.showInputDialog(null, "Masukan Tahun /n Contoh : 2017",
                        "Laporan Per-Bulan", JOptionPane.QUESTION_MESSAGE);
                String path="src/Report/lapbulanan.jasper";
                HashMap parameter = new HashMap();
                parameter.put ("pbulan", Response);
                parameter.put ("ptahun", Response1);
                JasperPrint print = JasperFillManager.fillReport(path, parameter, st.getConnection());
                this.dispose();
                JasperViewer.viewReport(print,false);
            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada"+ex);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPerbulanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                laporan2 dialog = new laporan2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerbulan;
    private javax.swing.JButton btnPerhari;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
