/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import DBO.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class PopupKas extends javax.swing.JDialog {
String [] data = new String[7];
    
PenerimaanKas pk;
    
    
private DefaultTableModel tblModel;

    /**
     * Creates new form PopupKas
     */
    public PopupKas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pk = new PenerimaanKas();
        tblModel = new DefaultTableModel();
        Table.setModel(tblModel);
        tblModel.addColumn("No. PenKas");
        tblModel.addColumn("Tanggal");
        tblModel.addColumn("Keterangan");
        tblModel.addColumn("Penerima");
        tblModel.addColumn("No Faktur");
        tblModel.addColumn("Terima Dari");
        tblModel.addColumn("Sebesar");
        setDefaultTableModel();
    }
    
    public void setDefaultTableModel(){
        try{
            koneksi knks = new koneksi();
            Connection con = knks.bukakoneksi();
            Statement st = con.createStatement();
            String sql;
            sql = "SELECT * FROM penerimakas";
            ResultSet res = st.executeQuery(sql);
            
            while(res.next()){
                data[0] = res.getString("no_kas");
                data[1] = res.getString("tanggal");
                data[2] = res.getString("keterangan");
                data[3] = res.getString("penerima");
                data[4] = res.getString("no_faktur");
                data[5] = res.getString("terima");
                data[6] = res.getString("sebesar");
                tblModel.addRow(data);
            }
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    public String[] getData()
    {
        return pk.getDataPopup();
    }
    
    public void hapusTable()
    {
        int rowCount=Table.getRowCount();
        for(int i=0; i<rowCount; i++)
        {
            tblModel.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbNoPenKas = new javax.swing.JComboBox<>();
        txtNoPenKas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        cbNoPenKas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNoPenKas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No. PenKas", "Nama Customer" }));

        txtNoPenKas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPenKasActionPerformed(evt);
            }
        });
        txtNoPenKas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPenKasKeyPressed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. PenKas", "Tanggal", "Keterangan", "Penerima", "No Faktur", "Terima Dari", "Sebesar"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbNoPenKas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtNoPenKas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 393, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNoPenKas, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtNoPenKas))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoPenKasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPenKasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPenKasActionPerformed

    private void txtNoPenKasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPenKasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            if(txtNoPenKas.getText().equals(""))
            {
                hapusTable();
                setDefaultTableModel();
            }
            else
            {
                hapusTable();
                String Key = null;
                if (cbNoPenKas.getSelectedIndex()==0)
                {Key="no_kas";}
                else if (cbNoPenKas.getSelectedIndex()==1)
                {Key="penerima";}
                try
                {
                    koneksi knks = new koneksi();
                    Connection con = knks.bukakoneksi();
                    Statement st = con.createStatement();
                    String SQL = "SELECT * FROM penerimakas WHERE "+ Key +" LIKE '"+txtNoPenKas.getText()+"'";
                    ResultSet res = st.executeQuery(SQL);
                    while (res.next())
                    {
                        data[0]=res.getString(1);
                        data[1]=res.getString(2);
                        data[2]=res.getString(3);
                        data[3]=res.getString(4);
                        data[4]=res.getString(5);
                        data[5]=res.getString(6);
                        tblModel.addRow(data);
                    }
                }
                catch(Exception e)
                {
                    System.err.println(e.getMessage());
                    JOptionPane.showMessageDialog(null, "Data Tidak Ada : " + e);
                }
            }
        }
    }//GEN-LAST:event_txtNoPenKasKeyPressed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int row = Table.getSelectedRow();
        if(row < 0)
        {
            return;
        }
        pk.setDataPopup(new String[]
            {
                tblModel.getValueAt (row,0).toString(),
                tblModel.getValueAt (row,1).toString(),
                tblModel.getValueAt (row,2).toString(),
                tblModel.getValueAt (row,3).toString(),
                tblModel.getValueAt (row,4).toString(),
                tblModel.getValueAt (row,5).toString(),
                tblModel.getValueAt (row,6).toString(),
            });
        dispose();
    }//GEN-LAST:event_TableMouseClicked

    private void TableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_TableComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupKas dialog = new PopupKas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> cbNoPenKas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNoPenKas;
    // End of variables declaration//GEN-END:variables
}
