/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import DBO.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class PopupPenjualan extends javax.swing.JDialog {
String [] data = new String[10];
    
Penjualan pn;
    
    
private DefaultTableModel tblModel;

    /**
     * Creates new form PopupPenjualan
     */
    public PopupPenjualan(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        this.pn = new Penjualan();
        initComponents();
        tblModel = new DefaultTableModel();
        Table.setModel(tblModel);
        tblModel.addColumn("No. Faktur");
        tblModel.addColumn("Tanggal");
        tblModel.addColumn("Nama Customer");
        tblModel.addColumn("ID. Barang");
        tblModel.addColumn("Nama Barang");
        tblModel.addColumn("Harga Barang");
        tblModel.addColumn("Quantity");
        tblModel.addColumn("Harga");
        tblModel.addColumn("Ppn");
        tblModel.addColumn("TotalHarga");
        setDefaultTableModel();
    }
    
    public void setDefaultTableModel(){
        try{
            koneksi knks = new koneksi();
            Connection con = knks.bukakoneksi();
            Statement st = con.createStatement();
            String sql;
            sql = "SELECT * FROM penjualan";
            ResultSet res = st.executeQuery(sql);
            
            while(res.next()){
                data[0] = res.getString("no_faktur");
                data[1] = res.getString("tanggal");
                data[2] = res.getString("nama_customer");
                data[3] = res.getString("id_barang");
                data[4] = res.getString("nama_barang");
                data[5] = res.getString("harga_barang");
                data[6] = res.getString("quantity");
                data[7] = res.getString("harga");
                data[8] = res.getString("ppn");
                data[9] = res.getString("total_harga");
                tblModel.addRow(data);
            }
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    public String[] getData()
    {
        return pn.getDataPopup();
    }
    
    public void hapusTable()
    {
        int rowCount=Table.getRowCount();
        for(int i=0; i<rowCount; i++)
        {
            tblModel.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbNoFaktur = new javax.swing.JComboBox<>();
        txtNoFaktur = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Penjualan - PT. Sugimoto Presisi Technologi");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        cbNoFaktur.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNoFaktur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No. Faktur", "Nama Customer" }));

        txtNoFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoFakturActionPerformed(evt);
            }
        });
        txtNoFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoFakturKeyPressed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Faktur", "Tanggal", "Nama Customer", "ID. Barang", "Nama Barang", "Harga Barang", "Quantity", "Harga", "Ppn", "Total Harga"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNoFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtNoFaktur))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoFakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoFakturActionPerformed

    private void txtNoFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoFakturKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            if(txtNoFaktur.getText().equals(""))
            {
                hapusTable();
                setDefaultTableModel();
            }
            else
            {
                hapusTable();
                String Key = null;
                if (cbNoFaktur.getSelectedIndex()==0)
                {Key="no_faktur";}
                else if (cbNoFaktur.getSelectedIndex()==1)
                {Key="nama_customer";}
                try
                {
                    koneksi knks = new koneksi();
                    Connection con = knks.bukakoneksi();
                    Statement st = con.createStatement();
                    String SQL = "SELECT * FROM penjualan WHERE "+ Key +" LIKE '"+txtNoFaktur.getText()+"'";
                    ResultSet res = st.executeQuery(SQL);
                    while (res.next())
                    {
                        data[0]=res.getString(1);
                        data[1]=res.getString(2);
                        data[2]=res.getString(3);
                        data[3]=res.getString(4);
                        data[4]=res.getString(5);
                        data[5]=res.getString(6);
                        data[6]=res.getString(7);
                        data[7]=res.getString(8);
                        data[8]=res.getString(9);
                        data[9]=res.getString(10);
                        tblModel.addRow(data);
                    }
                }
                catch(Exception e)
                {
                    System.err.println(e.getMessage());
                    JOptionPane.showMessageDialog(null, "Barang Tidak Ada : " + e);
                }
            }
        }
    }//GEN-LAST:event_txtNoFakturKeyPressed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
         int row = Table.getSelectedRow();
        if(row < 0)
        {
            return;
        }
        pn.setDataPopup(new String[]
            {
                tblModel.getValueAt (row,0).toString(),
                tblModel.getValueAt (row,1).toString(),
                tblModel.getValueAt (row,2).toString(),
                tblModel.getValueAt (row,3).toString(),
                tblModel.getValueAt (row,4).toString(),
                tblModel.getValueAt (row,5).toString(),
                tblModel.getValueAt (row,6).toString(),
                tblModel.getValueAt (row,7).toString(),
                tblModel.getValueAt (row,8).toString(),
                tblModel.getValueAt (row,9).toString(),
            });
        dispose();
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupPenjualan dialog = null;
                try {
                    dialog = new PopupPenjualan(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(PopupPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> cbNoFaktur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNoFaktur;
    // End of variables declaration//GEN-END:variables
}
